AllCops:
  NewCops: disable
  Exclude:
    - db/**/*
    - bin/**/*
    - config/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - spec/**/*
  AllowedPatterns:
    - '^#'

Layout/HashAlignment:
  Enabled: true
  Exclude:
    - lib/tasks/auto_annotate_models.rake

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/tasks/auto_annotate_models.rake
    - app/admin/**/*
    - app/views/admin/**/*
    - config/routes.rb
    - config/environments/*
    - db/schema.rb

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/FilePath:
  Enabled: false

require:
  - rubocop-rspec
  - rubocop-rails

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/auto_annotate_models.rake